server.port=8085

# Active profile — override with SPRING_PROFILES_ACTIVE=prod at runtime
spring.profiles.active=dev

# Flyway
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=auth
spring.flyway.create-schemas=true
